### ISSUE TITLE
Start Task menu from the system tray does not work with Plasma 5

### ISSUE THREAD

**Issue by amantia** [KDAB/Charm#246] opened 2015-11-24 09:09 UTC
As the title say, the menu is there, selecting it does not open the tasks submenu.

**Comment by frankosterfeld** [comment] 2015-11-24 09:11
So it contains no submenu? Can you add a screenshot? Also, is this 1.10.0 or master?

**Comment by frankosterfeld** [comment] 2015-11-24 09:14
Andras says it's 1.10.0, and that there's a menu entry with a submenu indicator, but no actual submenu.

**Comment by mgiroday** [comment] 2015-11-25 06:55
It looks like it is a known issue - should have been fixed by now.... will have a look.
see https://forum.qt.io/topic/49786/submenu-isn-t-shown-in-systray-context-menu-in-plasma-5

**Comment by mgiroday** [comment] 2015-11-25 07:10
and that looks like the fix: https://codereview.qt-project.org/#/c/103280/

**Comment by frankosterfeld** [comment] 2015-11-25 10:42
@amantia Which version of Frameworks/Plasma 5 are you using

**Comment by mgiroday** [comment] 2015-11-25 11:31
related to this:
https://bugreports.qt.io/browse/QTBUG-46293

**Comment by amantia** [comment] 2015-11-26 11:43
I have Qt 5.5.0, Plasma 5.4.3

**Comment by mgiroday** [comment] 2015-11-30 13:42
I give up on this one. My recommendation is that you assign this issue to a KDABian-KDE dev. 
It seems to be a KDE issue. My main constatation is that the events from the SystrayIcon context menu does are never propagated.
First of all we never receive the AboutToShow() signal which is connected to void ApplicationCore::slotStartTaskMenuAboutToShow().
It is probably not the cause of the bug but needs to be investigated. I could not find the reason for that after debugging Qt 5.5.1 source code.If we load the "Start Task" sub-menu actions directly in the context menu itself - they are displayed but they are never displayed as Actions from the "Start Task" menu ( depth 2 )
I give up for now with this issue - takes me too much time for too few results.

**Comment by mgiroday** [comment] 2015-12-03 10:39
https://bugreports.qt.io/browse/QTBUG-49743

here is the qt bug

**Comment by TheOneRing** [comment] 2016-02-15 08:55
Looks like the bug https://bugreports.qt.io/browse/QTBUG-49743 was resolved for 5.6.1

**Comment by hasselmm** [comment] 2016-02-15 09:42
Also occurs with Ubuntu's Unity since last week. Might be worth to flatten the menu. For versions of Qt older than 5.6.1, or in general even.

**Comment by frankosterfeld** [comment] 2016-04-15 16:05
I agree on flattening the menu, my idea would be to show the first 5 entries from the list (most recently used) and "Start Other task".

**Closed** 2017-01-31 13:23 UTC
Labels: Bug, Linux
